const APP_TITLE = `Let's Go`
const LOGIN_START = 'LOGIN_START'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'
const LOGOUT = 'LOGOUT'
const SIGNUP_START = 'SIGNUP_START'
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
const SIGNUP_FAILED = 'SIGNUP_FAILED'

export { APP_TITLE, LOGIN_START, LOGIN_SUCCESS, LOGIN_FAILED,
  LOGOUT, SIGNUP_START, SIGNUP_SUCCESS, SIGNUP_FAILED }
