/*
 * Copyright 2018, Socializing Syndicate Corp.
 */
const APP_TITLE = `Let's Go`
const DATE_FORMAT = 'MM/DD/YYYY'

const LOGIN_START = 'LOGIN_START'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'
const LOGOUT = 'LOGOUT'
const SIGNUP_START = 'SIGNUP_START'
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
const SIGNUP_FAILED = 'SIGNUP_FAILED'

const FETCH_EVENT_FEEDS_START = 'FETCH_EVENT_FEEDS_START'
const FETCH_EVENT_FEEDS = 'FETCH_EVENT_FEEDS'
const ADD_NEW_EVENT = 'ADD_NEW_EVENT'

export { APP_TITLE, DATE_FORMAT, LOGIN_START, LOGIN_SUCCESS, LOGIN_FAILED,
  LOGOUT, SIGNUP_START, SIGNUP_SUCCESS, SIGNUP_FAILED,
  FETCH_EVENT_FEEDS_START, FETCH_EVENT_FEEDS, ADD_NEW_EVENT
}
